author: Магомед Каитов
title: Эльбрус-термо
brand: Эльбрус-термо
description: Инкубаторы из Карачаево-Черкессии.
homeLink: "#/"
svgSprite:
  - arrow-bar-up
  - card-checklist
  - plus-square-dotted
  - book
  - signpost
  - person-plus
  - github
  - thermometer-half
navbarLinks:
  - icon: thermometer-half
    link: "#content/instruction.md"
    title: Инструкция
  - icon: person-plus
    link: "#community"
    title: Обратная связь
  - icon: github
    link: https://github.com/yababay/svelte-meets-yababay
    title: Проект на Гитхабе
tocToggle: Показать список товаров
tocHeader: "Список товаров:"
asideLinks:
  - title: Промишленные инкубаторы
    link: "#first"
    links:
      - link: "#content/first-first.md"
        title: Первая ссылка
        icon: book
      - link: "#content/first-second.md"
        title: Вторая ссылка
        icon: book
      - link: "#content/first-third.md"
        title: Третья ссылка
        icon: book
  - title: Для фермерских хозяйств
    link: "#second"
    links:
      - link: "#content/second-first.md"
        title: Первая ссылка
        icon: signpost
      - link: "#content/second-second.md"
        title: Вторая ссылка
        icon: signpost
      - link: "#content/second-third.md"
        title: Третья ссылка
        icon: signpost
  - title: Компактные инкубаторы
    link: "#third"
    links:
      - link: "#content/third-first.md"
        title: Первая ссылка
        icon: book
      - link: "#content/third-second-is-absent.md"
        title: Вторая ссылка
        icon: book
        style: danger
      - link: "#content/third-third.md"
        title: Третья ссылка
        icon: book
withBootstrap: true
withSvelte: false
withHashRouting: true
withHMFLayout: true
withComfortableReading: true
withCustomCss: true
headerLayout: brand-and-end-icons
mainLayout: offcanvas-and-article
footerLayout: simple-copyright
copyright: true
